# Generated by Django 5.2.8 on 2025-11-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Public forms are linked directly from the website (A1). A2 forms are private and used via invite link.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("tablestakes_score", models.FloatField(default=0)),
                ("commitment_score", models.FloatField(default=0)),
                ("nice_to_have_score", models.FloatField(default=0)),
                ("overall_score", models.FloatField(default=0)),
                ("recommendation", models.CharField(blank=True, max_length=20)),
                ("invite_token", models.UUIDField(blank=True, null=True, unique=True)),
                ("invited_to_second_stage", models.BooleanField(default=False)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="applications.formdefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("help_text", models.TextField(blank=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short text"),
                            ("long_text", "Long text"),
                            ("integer", "Integer"),
                            ("boolean", "Yes/No (checkbox)"),
                            ("choice", "Single choice"),
                            ("multi_choice", "Multiple choice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier for grading (e.g. 'e2_hours_per_week')."
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="applications.formdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("form", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "value",
                    models.CharField(
                        help_text="Machine-readable value stored in Answer.value",
                        max_length=100,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="applications.question",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="applications.application",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.question",
                    ),
                ),
            ],
        ),
    ]
