# Generated by Django 6.0 on 2025-12-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("start_month", models.CharField(max_length=30)),
                ("end_month", models.CharField(max_length=30)),
                ("year", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="is_master",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=models.SlugField(
                help_text="Stable identifier for grading (e.g. 'm_a1_requisitos')."
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forms",
                to="applications.formgroup",
            ),
        ),
    ]
