# Generated by Django 6.0 on 2026-01-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_formgroup_formdefinition_is_master_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="accepting_responses",
            field=models.BooleanField(default=True),
        ),
    ]
