# Generated by Django 6.0 on 2026-01-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_gradedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_slug", models.CharField(blank=True, default="", max_length=100)),
                ("app_id", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("log_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
