# Generated by Django 6.0 on 2026-01-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_gradingjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradedfile",
            name="file",
        ),
        migrations.AddField(
            model_name="gradedfile",
            name="csv_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
