# Generated by Django 6.0 on 2026-01-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_remove_gradedfile_file_gradedfile_csv_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradingjob",
            name="app_id",
            field=models.IntegerField(
                blank=True,
                help_text="Application ID if this job grades a single application.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gradingjob",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="gradingjob",
            name="form_slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Form slug being graded (e.g. G6_E_A2). Empty if single-app job.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="gradingjob",
            name="log_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Append-only job log (progress, errors, tracebacks).",
            ),
        ),
        migrations.AlterField(
            model_name="gradingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
