# Generated by Django 6.0 on 2026-01-27 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0007_alter_gradingjob_app_id_alter_gradingjob_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradedfile",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.application",
            ),
        ),
    ]
