# Generated by Django 6.0 on 2026-01-28 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_alter_gradedfile_application"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradedfile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="gradedfile",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graded_files",
                to="applications.application",
            ),
        ),
        migrations.AlterField(
            model_name="gradedfile",
            name="form_slug",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
