# Generated by Django 6.0 on 2026-03-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_formgroup_reminder_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='second_stage_reminder_due_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Automatic follow-up reminder due time for invited A1 applicants.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='second_stage_reminder_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the automatic A1->A2 reminder was sent.', null=True),
        ),
    ]
