# Generated by Django 6.0 on 2026-04-06 20:14

import django.db.models.deletion
from django.db import migrations, models


def _seed_task_types_and_backfill(apps, schema_editor):
    task_type_model = apps.get_model("applications", "TaskType")
    user_task_model = apps.get_model("applications", "UserTask")

    default_types = [
        {
            "slug": "general",
            "name": "General",
            "position": 10,
            "is_active": True,
            "is_revision_type": False,
        },
        {
            "slug": "follow_up",
            "name": "Follow up",
            "position": 20,
            "is_active": True,
            "is_revision_type": False,
        },
        {
            "slug": "website_revision",
            "name": "Website revision",
            "position": 30,
            "is_active": True,
            "is_revision_type": True,
        },
    ]

    slug_to_obj = {}
    for cfg in default_types:
        obj, _ = task_type_model.objects.get_or_create(
            slug=cfg["slug"],
            defaults={
                "name": cfg["name"],
                "position": cfg["position"],
                "is_active": cfg["is_active"],
                "is_revision_type": cfg["is_revision_type"],
            },
        )
        slug_to_obj[cfg["slug"]] = obj

    for task in user_task_model.objects.all().iterator():
        if task.task_type_ref_id:
            continue
        tt = slug_to_obj.get(task.task_type or "")
        if tt:
            task.task_type_ref_id = tt.id
            task.save(update_fields=["task_type_ref"])


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0026_usertask"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_revision_type",
                    models.BooleanField(
                        default=False,
                        help_text="Used by the Website Revisions page as its default task type.",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "name", "id"],
            },
        ),
        migrations.AddField(
            model_name="usertask",
            name="impact",
            field=models.TextField(
                blank=True, help_text="What impact this task has and why it matters."
            ),
        ),
        migrations.AddField(
            model_name="usertask",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="task_type",
            field=models.CharField(db_index=True, default="general", max_length=20),
        ),
        migrations.AddField(
            model_name="usertask",
            name="task_type_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="applications.tasktype",
            ),
        ),
        migrations.RunPython(_seed_task_types_and_backfill, _noop_reverse),
    ]
