# Generated by Django 6.0 on 2026-04-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0029_alter_usertask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In progress"),
                    ("unavailable", "Unavailable"),
                    ("revision_needed", "Revision Needed"),
                    ("done", "Completed"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
