# Generated by Django 6.0 on 2026-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0030_alter_usertask_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantEmailStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("participated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Participant Email Status",
                "verbose_name_plural": "Participant Email Statuses",
                "ordering": ["email"],
            },
        ),
    ]
