# Generated by Django 6.0 on 2026-04-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0031_participantemailstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupParticipantList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mentoras_emails_text", models.TextField(blank=True)),
                ("emprendedoras_emails_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_list",
                        to="applications.formgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Participant List",
                "verbose_name_plural": "Group Participant Lists",
                "ordering": ["-group__number"],
            },
        ),
    ]
