# Generated by Django 6.0 on 2026-04-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0032_groupparticipantlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupparticipantlist",
            name="emprendedoras_sheet_rows",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="groupparticipantlist",
            name="mentoras_sheet_rows",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
