# Generated by Django 6.0 on 2026-04-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0033_groupparticipantlist_emprendedoras_sheet_rows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertask",
            name="hours_estimate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
