# Generated by Django 6.0 on 2026-04-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0034_usertask_hours_estimate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertask",
            name="priority",
            field=models.CharField(
                choices=[
                    ("urgent", "P1"),
                    ("high", "P2"),
                    ("medium", "P3"),
                    ("low", "P4"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
            ),
        ),
    ]
