# Generated by Django 6.0 on 2026-04-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0035_alter_usertask_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingjob",
            name="priority_emails_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Normalized newline-separated emails to force into Priority status during grading.",
            ),
        ),
    ]
