# Generated by Django 6.0 on 2026-04-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0036_gradingjob_priority_emails_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="DropboxSignWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=120)),
                ("event_time", models.CharField(blank=True, default="", max_length=64)),
                (
                    "event_hash",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "signature_request_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("signer_emails_text", models.TextField(blank=True, default="")),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "payload_digest",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("hash_verified", models.BooleanField(db_index=True, default=False)),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("marked_count", models.PositiveIntegerField(default=0)),
                ("process_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Dropbox Sign Webhook Event",
                "verbose_name_plural": "Dropbox Sign Webhook Events",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="participantemailstatus",
            name="contract_signature_request_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="participantemailstatus",
            name="contract_signed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="participantemailstatus",
            name="contract_signed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="participantemailstatus",
            name="contract_source",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
