# Generated by Django 6.0 on 2026-05-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0043_backfill_formdefinition_thanks_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="email_a1_approved_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional custom HTML body for A1 approved/invite email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a1_approved_subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional custom subject for A1 approved/invite email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a1_rejected_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional custom HTML body for A1 rejected email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a1_rejected_subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional custom subject for A1 rejected email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a1_to_a2_reminder_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional custom HTML body for automatic A1→A2 reminder email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a1_to_a2_reminder_subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional custom subject for automatic A1→A2 reminder email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a2_final_reminder_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional custom HTML body for manual/final A2 reminder email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a2_final_reminder_subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional custom subject for manual/final A2 reminder email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a2_received_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional custom HTML body for A2 received/valid submission email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a2_received_subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional custom subject for A2 received/valid submission email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a2_rejected_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional custom HTML body for A2 rejected/disqualified email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="email_a2_rejected_subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional custom subject for A2 rejected/disqualified email. Supports placeholders like {{ group_num }}, {{ group_label }}, {{ track_label }}, {{ form_name }}, {{ role_word }}, {{ a2_link }}, {{ deadline_text }}, {{ respond_by_day }}, {{ respond_by_month }}, {{ respond_by_year }}.",
                max_length=255,
            ),
        ),
    ]
