# Generated by Django 6.0 on 2026-05-29 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0045_backfill_formdefinition_email_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantSheetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("mentoras", "Mentoras"),
                            ("emprendedoras", "Emprendedoras"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("rows", models.JSONField(blank=True, default=list)),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "action",
                    models.CharField(blank=True, default="autosave", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_sheet_versions",
                        to="applications.formgroup",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participant_sheet_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant Sheet Version",
                "verbose_name_plural": "Participant Sheet Versions",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["group", "track", "-created_at"],
                        name="application_group_i_7f065f_idx",
                    )
                ],
            },
        ),
    ]
