# Generated by Django 6.0 on 2026-06-26 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0050_alter_storedemailtemplate_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationGradingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(blank=True, default="", max_length=80)),
                (
                    "max_total_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("rubric_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_config",
                        to="applications.formdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["form__slug"],
            },
        ),
        migrations.CreateModel(
            name="PairingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(blank=True, default="", max_length=80)),
                ("top_k_for_ai", models.PositiveIntegerField(default=3)),
                ("availability_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_config",
                        to="applications.formgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-group__number"],
            },
        ),
        migrations.CreateModel(
            name="PairingAIComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=160)),
                ("emprendedora_question_slug", models.SlugField(max_length=80)),
                ("mentora_question_slug", models.SlugField(max_length=80)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=6, max_digits=8),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional AI prompt. Use {{ label }}, {{ mentor_text }}, {{ entrepreneur_text }}. The response must include 'Score:' and 'Reasoning:' lines.",
                    ),
                ),
                ("output_key", models.SlugField(blank=True, default="", max_length=80)),
                ("active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_comparisons",
                        to="applications.pairingconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="PairingPriorityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=160)),
                ("emprendedora_question_slug", models.SlugField(max_length=80)),
                ("mentora_question_slug", models.SlugField(max_length=80)),
                (
                    "comparison_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact answer match"),
                            ("availability_overlap", "Availability overlap"),
                            ("business_age", "Mentor experience covers business age"),
                        ],
                        default="exact",
                        max_length=30,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                ("required", models.BooleanField(default=False)),
                ("output_key", models.SlugField(blank=True, default="", max_length=80)),
                ("active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priority_rules",
                        to="applications.pairingconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="GradingCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_slug", models.SlugField(max_length=80)),
                ("label", models.CharField(blank=True, default="", max_length=160)),
                (
                    "criterion_type",
                    models.CharField(
                        choices=[
                            ("structured", "Structured / deterministic"),
                            ("ai_text", "AI paragraph score"),
                        ],
                        default="structured",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional AI prompt for paragraph questions. Use {{ criterion }} and {{ response }}. The response must still ask for 'Score:' and 'Explanation:' lines.",
                    ),
                ),
                ("negative_allowed", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="applications.applicationgradingconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "unique_together": {("config", "question_slug")},
            },
        ),
    ]
