# Generated by Django 6.0 on 2026-06-26 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0051_applicationgradingconfig_pairingconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingResponseWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("active", models.BooleanField(default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "choice",
                    models.ForeignKey(
                        help_text="One of the predefined choices for the selected question.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_response_weights",
                        to="applications.choice",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_weights",
                        to="applications.applicationgradingconfig",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Dropdown/checkbox question whose stored answer should receive this weight.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_response_weights",
                        to="applications.question",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "unique_together": {("config", "question", "choice")},
            },
        ),
    ]
